---
- name: 'Restart systemd-journal-upload'
  ansible.builtin.systemd:
    name: 'systemd-journal-upload'
    state: 'restarted'
    daemon_reload: true

- name: 'Restart systemd-journald'
  ansible.builtin.systemd:
    name: 'systemd-journald'
    state: 'restarted'

- name: "Enforce log retention with journalctl"
  ansible.builtin.shell: |
    journalctl --vacuum-time={{ journald_client_retention }}
  register: _journalctl_vacuum_result
  changed_when: "'Vacuuming done' in _journalctl_vacuum_result.stdout"
